import sqlite3
from google import genai
import streamlit as st
from dotenv import load_dotenv
import os 

load_dotenv()
client=genai.Client(api_key=os.getenv("API_KEY"))

def google_response(Inputs):
    response=client.models.generate_content(model="gemini-2.5-flash",contents=Inputs)
    return response.text

prompt='''
You are an expert in converting English questions to SQL query!
The SQL database has the name Naresh_it_employee.db, There is only one table on which you have do operation that is Employees
and has the following columns - Name, Role, Salary_pm

For example,
Example 1 - How many entries of records are present?,
the SQL command will be something like this SELECT COUNT (*) FROM Employees ;
Example 2 - Tell me all the employees working in Data Science role?, the SQL command will be something like this SELECT * FROM Employees
where Role="Data Science";
also the sql code should not have '' and ; in beginning or end and sql word in output
'''
Explain=''' You are great communicator like Shashi Tharoor but with vocabs that people understand 
Explain the generated response in human like form in layman Language that people understand 
use the coulmn name to tell what is the names and be intutive and interactive answer to provide a good 
insights about the answer that is given by the other functions.
I just want the results and it insights not the whole query explaination everthing and sum up the answer in 150 words and if
explictily ask for the longer deatiled output you can give them.
There are Four arguments first arguments is for the user inputs his question and prompt 
is the basis for creating the sql query and then second argument is the Explain which gives instruction 
of how this function will generate english sentences  for the user and Third argument response is the content 
generated by the gemini the  SQL query and itr will be fed to the database and furth argument gives the result 
when that sql query is fed to the database. Fifth is the Instructons'''



def read_sql(db,query):
    con=sqlite3.connect(db)
    cur=con.cursor()
    cur.execute(query) 
    rows=cur.fetchall()
    con.commit()
    con.close()
    return rows

#def result_response(Input1):
#    response1=client.models.generate_content(model='gemini-2.5-flash',contents=Input1)
#    return response1.text


st.title("Databse info retrieval")
Question=st.text_input("What do you want to ask from database")

Inputs=[Question,prompt]
button=st.button("Ask Question")
if button:
    response=google_response(Inputs)
    res=read_sql("Naresh_it_employee.db",response)

    result_sql=["\n".join(str(row)) for row in res]
    
    Input1=[Explain,*[Inputs],response,result_sql]
    
    result=google_response(Input1)
    st.write(result)